# Generated by Django 4.1.3 on 2022-11-02 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards_app', '0002_rename_back_text_card_definition_and_more'),
        ('collections_app', '0003_collections_seed')
    ]

    operations = [
        migrations.RunSQL('''
            insert into flashcards_database.cards_app_card (id, word, definition, collection_id) values (1, 'What is Flutter?', 'Flutter is an open-source UI software development kit created by Google. It is used to develop cross platform applications for Android, iOS, Linux, macOS, Windows, Google Fuchsia, and the web from a single codebase.', 1);
            insert into flashcards_database.cards_app_card (id, word, definition, collection_id) values (2, 'What is Dart ?', 'Dart is a programming language designed for client development, such as for the web and mobile apps.', 1);
            insert into flashcards_database.cards_app_card (id, word, definition, collection_id) values (3, 'What is a widget?', 'Widgets are the central class hierarchy in the Flutter framework. A widget is an immutable description of part of a user interface.', 1);
            insert into flashcards_database.cards_app_card (id, word, definition, collection_id) values (4, 'What is CSS?', 'Cascading Style Sheets is a style sheet language used for describing the presentation of a document written in a markup language such as HTML or XML.', 2);
            insert into flashcards_database.cards_app_card (id, word, definition, collection_id) values (5, 'What is a class?', 'A CSS class is an attribute used to define a group of HTML elements in order to apply unique styling and formatting to those elements with CSS.', 2);
            insert into flashcards_database.cards_app_card (id, word, definition, collection_id) values (6, 'Id vs Class', 'While an ID is specific to a single element, classes can be assigned to multiple elements on a page or throughout the website.', 2);
            insert into flashcards_database.cards_app_card (id, word, definition, collection_id) values (7, 'What is Pandas?', 'Pandas is a software library written for the Python programming language for data manipulation and analysis.', 3);
            insert into flashcards_database.cards_app_card (id, word, definition, collection_id) values (8, 'Pandas DataFrame', 'DataFrame is a 2-dimensional labeled data structure with columns of potentially different types.', 3);
            insert into flashcards_database.cards_app_card (id, word, definition, collection_id) values (9, 'Why use "read_csv"?', 'o access data from the CSV file, we require a function read_csv() that retrieves data in the form of the Dataframe.', 3);
        ''')
    ]
