# Generated by Django 4.1.3 on 2022-11-02 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collections_app', '0002_rename_name_collection_title'),
    ]

    operations = [
        migrations.RunSQL('''
        insert into flashcards_database.collections_app_collection (id, title) values (1, 'Flutter');
        insert into flashcards_database.collections_app_collection (id, title) values (2, 'CSS');
        insert into flashcards_database.collections_app_collection (id, title) values (3, 'Pandas');
        ''')
    ]
